server:
  port: 1000
  ip:  127.0.0.1
spring:
  application:
    name: PAMA-DSP-ADMIN-WEB
  boot:
    admin:
      url: http://${server.ip}:${server.port}
      username: "${security.user.name}"       #These two are needed so that the client
      password: "${security.user.password}"   #can register at the protected server api
    client:
       metadata:
          user.name: "${security.user.name}"          #These two are needed so that the server
          user.password:  "${security.user.password}" #can access the proteceted client endpoints
security:
  user:
    name: admin
    password: admin

  basic:
    enabled: false

#开启shutdown的安全验证
endpoints:
  health:
    sensitive: true
  cors:
    allowed-methods: HEAD,GET,POST
  shutdown:
    enabled: true #启用shutdown
    sensitive: true #禁用密码验证

# 引用监控限制内容Map <Key String>
info:
  artifact : mi-spring-boot-admin
  name: ${spring.application.name}
  description: 应用监控中心
  version : V1.0

#logging:
#  file: "traget/mi-spring-boot-admin.log"

management:
  security:
    enabled: false
    roles: SUPERUSER
  endpoints:
    web:
       exposeure:
         include: '*'
  endpoint:
     health:
        show-details: always



